<?php

require_once( drupal_get_path ( 'module', 'drupalUtils' ) . "/path/path.inc" );
require_once( drupal_get_path ( 'module', 'drupalUtils' ) . "/utils/file.inc" );
require_once( drupal_get_path ( 'module', 'drupalUtils' ) . "/utils/views.inc" );
require_once( drupal_get_path ( 'module', 'drupalUtils' ) . "/generate/string.inc" );
require_once( drupal_get_path ( 'module', 'drupalUtils' ) . "/content/nodeType.inc" );
require_once( drupal_get_path ( 'module', 'drupalUtils' ) . "/content/book.inc" );
require_once( drupal_get_path ( 'module', 'drupalUtils' ) . "/content/node.inc" );
require_once( drupal_get_path ( 'module', 'drupalUtils' ) . "/content/file.inc" );
require_once( drupal_get_path ( 'module', 'drupalUtils' ) . "/content/user.inc" );
require_once( drupal_get_path ( 'module', 'drupalUtils' ) . "/content/taxonomy.inc" );
require_once( drupal_get_path ( 'module', 'drupalUtils' ) . "/content/fields.inc" );

/**
 * Util method to debug objects etc with core debug
 *
 * @param $value
 * @param string $id
 */
function drupal_set_message_array ( $value, $id="Debug util" ) {
    include_once DRUPAL_ROOT . '/includes/utility.inc';

    debug($value, $id, TRUE);
}

/**
 * Clear Drupal shortcut
 */
function clearInitDrupal() {

    //Cleanup and init everything you can think of
    drupal_flush_all_caches();
    drupal_theme_rebuild ();
    menu_rebuild ();
    drupal_cron_cleanup ();
    drupal_cron_run ();
    
}
